[codelinks]
# Configuration for source tracing
set_local_url = false             # Set to true to enable local code html and URL generation
local_url_field = "local"        # Need's field name for local URL
set_remote_url = true           # Set to true to enable remote url to be generated
remote_url_field = "remote-url" # Need's field name for remote URL


[codelinks.projects.x-as-code-cpp]
remote_url_pattern = "https://github.com/useblocks/x-as-code/blob/{commit}/{path}#L{line}" # URL pattern for remote source code

[codelinks.projects.x-as-code-cpp.source_discover]
src_dir = "../src" # Relative path from this TOML config to the source directory
include = [
    "*.cpp",
    "*.h"
]
exclude=[]
gitignore = true
comment_type = "cpp"

[codelinks.projects.x-as-code-cpp.analyse]
get_need_id_refs = true
get_oneline_needs = true
get_rst = true

[codelinks.projects.x-as-code-cpp.analyse.oneline_comment_style]
# start_sequence = "@"
# end_sequence for the online comments; default is an os-dependant newline character
field_split_char = ","
needs_fields = [
   { "name" = "title", "type" = "str" },
   { "name" = "id", "type" = "str" },
   { "name" = "type", "type" = "str", "default" = "impl" },
   { "name" = "links", "type" = "list[str]", "default" = [] },
]